version: '3'

services:
  database:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Teste#1234.
      MYSQL_DATABASE: appvendas
      MYSQL_USER: vendas
      MYSQL_PASSWORD: vendas